#!/bin/bash

# Install Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Turn off brew analytics
brew analytics off

# Install iTerm2
brew install --cask iterm2

# (at this point we need to close terminal and open iterm)

# Install zsh
brew install zsh

# Set zsh as the default terminal environment
# a. Go to iTerm2 preferences.
# b. Head to Profiles -> General.
# c. Paste /usr/local/bin/zsh in the Command textbox and restart iTerm2.

#Install Oh My Zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Install Visual Studio Code
brew install --cask visual-studio-code

# Install Karabiner
brew install --cask karabiner-elements

#Install KeePassXC
brew install --cask keepassxc

# Install Alt-Tab
brew install --cask alt-tab

# Add these exceptions to Alt-Tab:
#   com.McAfee.McAfeeSafariHost
#   com.adobe.acc.AdobeCreativeCloud

# Install python
brew install python

# Install Powerlevel10k
git clone https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k
# Change ~/.zshrc to include:
ZSH_THEME="powerlevel10k/powerlevel10k"