#!/bin/sh

mkdir ~/certs

openssl genrsa -des3 -out ~/certs/k-fam.com.key 2048
openssl req -x509 -new -nodes -key ~/certs/k-fam.com.key -sha256 -days 1825 -out ~/certs/k-fam.com.pem
sudo security add-trusted-cert -d -r trustRoot -k "/Library/Keychains/System.keychain" ~/certs/k-fam.com.pem

